# Start from the official Ubuntu Bionic (18.04 LTS) image
FROM ubuntu:bionic

# Install any extra things we might need
RUN apt-get update \
	&& apt-get install -y \
		vim \
		ssh \
		sudo \
		wget \
        libtbb-dev \
		software-properties-common ;\
		rm -rf /var/lib/apt/lists/*

# Create a new user called yyhx78
RUN useradd --user-group --create-home --shell /bin/bash yyhx78 ;\
	echo "yyhx78 ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install OpenFOAM v7 (without ParaView)
# including configuring for use by user=yyhx78
# plus an extra environment variable to make OpenMPI play nice
RUN sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -" ;\
	add-apt-repository http://dl.openfoam.org/ubuntu ;\
	apt-get update ;\
	apt-get install -y --no-install-recommends openfoam7 ;\
	rm -rf /var/lib/apt/lists/* ;\
    rm -rf /opt/openfoam7/test ;\
    rm -rf /opt/openfoam7/tutorials ;\
    rm -rf /opt/openfoam7/doc ;\
    rm -rf /opt/openfoam7/bin ;\
    rm -rf /opt/openfoam7/applications ;\
    rm -rf /opt/openfoam7/platforms/linux64GccDPInt32Opt/bin ;\
	echo "source /opt/openfoam7/etc/bashrc" >> ~yyhx78/.bashrc ;\
	echo "export OMPI_MCA_btl_vader_single_copy_mechanism=none" >> ~yyhx78/.bashrc

# set the default container user to yyhx78
USER yyhx78

# to build the image: docker build -f DockerFile_base . -t yyhx78/spps_base
# to push: docker push yyhx78/spps_base;
